name: Image build and push 
on:
  pull_request:
    paths:
      - 'tests/**'
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'docker/**'
  workflow_run:
    workflows: ["Test auto version release"]
    branches: [main]
    types:
      - completed
env:
  IMAGE_NAME: opendatacube/datacube-statistician

permissions:
  contents: read
  packages: write

jobs:
  set_tags:
    if: github.ref == 'refs/heads/main'
      && (github.event_name == 'push' || (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push image to dockerhub
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: ./docker
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ env.IMAGE_NAME }}
