name: Build and test wheels 

on:
  push:
    branches-ignore: [main]
    paths:
      - '**'
    tags:
      - '**'

 
permissions:
  contents: read
  packages: read

jobs:
  build_wheels:
    if: |
      github.event_name == 'push' || (github.ref == 'refs/heads/main'
        && github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: build wheels
        run: |
          echo "build wheels either on push or only on new release"
