name: Build and test wheels 

on:
  push:
    branches-ignore: [main]
    paths:
      - '**'
    tags:
      - '**'
  workflow_run:
    workflows: ["Create a new tag"]
    types:
      - completed

 
permissions:
  contents: read
  packages: read

jobs:
  build_wheels:
    if: |
      github.event_name == 'push' || (github.ref == 'refs/heads/main'
        && github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: build wheels
        run: |
          echo "build wheels either on push or only on new release"
