name: Test auto version release
on:
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade \
           toml \
           wheel \
           twine \
           packaging
          python -m pip freeze

      - name: Verify Changed files
        uses: tj-actions/changed-files@v32
        id: verify-changed-version
        with:
          files: |
              dummy/**

      - name: Patch Package Versions when code change.
        if: steps.verify-changed-version.outputs.any_changed == 'true'
          && !(github.ref == 'refs/heads/main')
        id: patch-version
        run: |
          # -1: auto increment of patch number
          # other positive integers: set the patch number accordingly
          python ./scripts/patch_version.py -1 dummy/_version.py
          TAG=$(cat dummy/_version.py  | sed 's/[^0-9|.]//g')
          git config --global user.email "$GITHUB_ACTOR@auto.noreply"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Bump version to $TAG"
          git push origin HEAD:${{ github.head_ref }} --follow-tags

      - name: Push and tag versions
        if: steps.verify-changed-version.outputs.any_changed == 'true'
          && github.ref == 'refs/heads/main'
        id: push-new-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: autoaction
        run: |
          TAG=$(cat dummy/_version.py  | sed 's/[^0-9|.]//g')
          git tag $TAG
          git push origin --tags
          echo "NEW=true" >> $GITHUB_OUTPUT
    outputs:
      new_version: ${{ steps.push-new-tag.outputs.NEW }}

  publish:
    needs: [bump_version]
    runs-on: ubuntu-latest
    if: |
      (needs.bump_version.result == 'success') &&
      (needs.bump_version.outputs.new_version) 
    steps:
      - uses: actions/checkout@v2
      - name: Publish if there is new version
        run: |
          echo "${{ needs.bump_version.outputs.new_version }}"
