name: Test auto version release
on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branch-ignores: [main]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Fetch tags
        run: |
          git fetch --tags origin
          git tag

      - name: Verify Changed files
        uses: tj-actions/changed-files@v34
        id: verify-changed-version
        with:
          files: |
              dummy/**

      - name: Patch Package Versions when code change.
        if: steps.verify-changed-version.outputs.any_changed == 'true'
          && (github.event_name == 'pull_request')
        id: patch-version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
