name: Test publish

on:
  release:
    types: [published]

jobs:
  publish_new_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "TAG=$github.ref_name" \
          >> $GITHUB_OUTPUT
          ehco $GITHUB_OUTPUT
