name: Publish to S3 and PyPI

on:
  workflow_run:
    workflows: ["Build and test wheels"]
    branches: [main]
    types:
      - completed

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered after successful Run Code Checks"
