name: Publish to S3 and PyPI

on:
  push:
    tags:
      - "**"
  workflow_run:
    workflows: ["Build and test wheels"]
    types: [completed]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event payload
        run: |
          echo "event: ${{ github.event.workflow_run.event }}"
          echo "ref: ${{ github.event.workflow_run.ref }}"
          echo "head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "conclusion: ${{ github.event.workflow_run.conclusion }}"
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing for tag SHA ${{ github.event.workflow_run.head_sha }}"

